### ISSUE TITLE
New Appliances

### ISSUE THREAD

**Issue by shaun-blake** [shaun-blake/harbor-view#31]
This could probably be done at any time but some would be easier at certain times.

- [x] Stove - any time but probably before #17.
- [x] Dishwasher - along with #24 
- [x] Fridge - any time but before #21 to make plumbing easier.
- [x] Washer and Dryer any time (if at all) but probably at the time of #16
